### ISSUE TITLE
Question about the 3d co-ordinate of skeleton and joint structure

### ISSUE THREAD

**Issue by timtensor** [mengyingfei/pose-3d-pytorch-ros#2]
Hi 
Is it possible to export the (x,y,z) co -ordinate of the predicted 3D pose of the entire structure ? And if so how is it to be done ? 
The second question is how is the joint structure of the 3d pose ?

**Comment by fabro66** [comment]
First question:
It can export the (x, y, z) coordinate of the predicted 3D pose. 
You can look the file :pose-3d-pytorch-ros/src/rviz/tf_pose_broadcaster.py 

Second question:
All pose of joints based on pelvis. The pose of pelvis  is (0, 0, 0).  
You can look the file :pose-3d-pytorch-ros/src/rviz/tf_pose_broadcaster.py

**Comment by fabro66** [comment]
> Hi
> Is it possible to export the (x,y,z) co -ordinate of the predicted 3D pose of the entire structure ? And if so how is it to be done ?
> The second question is how is the joint structure of the 3d pose ?

First question:
It can export the (x, y, z) coordinate of the predicted 3D pose.
You can look the file :pose-3d-pytorch-ros/src/rviz/tf_pose_broadcaster.py

Second question:
All pose of joints based on pelvis. The pose of pelvis is (0, 0, 0).
You can look the file :pose-3d-pytorch-ros/src/rviz/tf_pose_broadcaster.py
